// Regenerates one favor-gated action per price tier (Rome Cloud fixes the
// price in action.yaml) and the matching `actions:` list in app.yaml.
// Usage: pnpm gen:tiers   (tiers come from src/shared/model.ts)
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const model = readFileSync(join(root, "src/shared/model.ts"), "utf8");
const tiers = JSON.parse(/export const TIERS = (\[[^\]]+\])/.exec(model)[1]);
const fmt = (n) => n.toLocaleString("en-US");
const word = (n) => (n === 1 ? "favor" : "favors");

const actionsDir = join(root, "src/actions");
for (const dir of readdirSync(actionsDir)) if (dir.startsWith("pay-")) rmSync(join(actionsDir, dir), { recursive: true });

for (const n of tiers) {
  const dir = join(actionsDir, `pay-${n}`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, "action.yaml"),
    `# Generated by scripts/gen-tiers.mjs — edit the generator, not this file.
name: pay_${n}
type: custom
visibility: explicit
description: >-
  Settle a Settle favor request priced at ${fmt(n)} ${word(n)}. Favor-gated — the
  payer approves ${fmt(n)} ${word(n)} on Rome Cloud before it runs. Started only by
  the Settle pay page; idempotent per payment.
entry: ./index.ts
complexity: simple
speed: fast
reliability: high
sideEffects: write
favorRequirement:
  amount: ${n}
  title: Favor request · ${fmt(n)} ${word(n)}
  summary: >-
    A thank-you for work already done. The favors go to the person who sent
    you this request.
  displayFields:
    - label: For
      from: $.item
    - label: Paid to
      from: $.payee
    - label: Reference
      from: $.reference
`,
  );
  writeFileSync(
    join(dir, "index.ts"),
    `// Generated by scripts/gen-tiers.mjs — edit src/lib/pay-action.ts instead.
import type { Action, ActionConfig, AppActionRuntimeDeps } from "@rome-os/app-runtime";
import { createPayAction } from "../../lib/pay-action.js";

export function createAction(config: ActionConfig, deps: AppActionRuntimeDeps): Action {
  return createPayAction(config, deps);
}
`,
  );
}

const appYaml = join(root, "app.yaml");
const yaml = readFileSync(appYaml, "utf8");
const list = tiers.map((n) => `  - actions/pay-${n}`).join("\n");
const next = yaml.replace(/actions:\n(?:  - .*\n?)+/, `actions:\n${list}\n`);
writeFileSync(appYaml, next);
console.log(`Generated ${tiers.length} tier actions.`);
