// Generated by scripts/gen-tiers.mjs — edit src/lib/pay-action.ts instead.
import type { Action, ActionConfig, AppActionRuntimeDeps } from "@rome-os/app-runtime";
import { createPayAction } from "../../lib/pay-action.js";

export function createAction(config: ActionConfig, deps: AppActionRuntimeDeps): Action {
  return createPayAction(config, deps);
}
