/**
 * Render the self-contained slide deck (an HTML document generated by
 * `src/lib/slides.ts`, with its own inline controller) inside a sandboxed
 * iframe. `allow-scripts` lets that controller run; we deliberately omit
 * `allow-same-origin` so the model-generated document cannot reach the host.
 */
export function SlidesView({ html }: { html: string }) {
  return (
    <div className="space-y-2">
      <p className="text-sm text-muted-foreground">
        Use the arrow keys to move between slides. Click into the stage first to focus it.
      </p>
      <div className="overflow-hidden rounded-lg border bg-card">
        <iframe
          title="Slides"
          srcDoc={html}
          sandbox="allow-scripts"
          className="h-[70vh] w-full"
        />
      </div>
    </div>
  );
}
