import {
  createAppLogger,
  type Action,
  type ActionConfig,
  type ActionResult,
  type AppActionRuntimeDeps,
  type PersonMappingRepository,
  type SettingsRepository,
} from "@rome-os/app-runtime";

const log = createAppLogger("daily_gre_word");

// ---------------------------------------------------------------------------
// GRE Word List
// ---------------------------------------------------------------------------

interface GreWord {
  word: string;
  pronunciation: string;
  pos: string;
  definition: string;
  example: string;
  etymology: string;
  synonyms: string[];
}

const GRE_WORDS: GreWord[] = [
  {
    word: "abscond",
    pronunciation: "/əb-ˈskänd/",
    pos: "verb",
    definition:
      "To leave hurriedly and secretly, typically to escape from custody or avoid arrest.",
    example: "The embezzler absconded with the company's funds before the audit.",
    etymology: "Latin abscondere — ab (away) + condere (to hide)",
    synonyms: ["flee", "bolt", "decamp"],
  },
  {
    word: "aberrant",
    pronunciation: "/ə-ˈber-ənt/",
    pos: "adjective",
    definition: "Departing from an accepted standard; deviating from the normal type.",
    example: "The aberrant test results prompted the scientists to recheck their methodology.",
    etymology: "Latin aberrare — ab (away) + errare (to wander)",
    synonyms: ["anomalous", "atypical", "deviant"],
  },
  {
    word: "acumen",
    pronunciation: "/ˈak-yə-mən/",
    pos: "noun",
    definition:
      "The ability to make good judgments and quick decisions, typically in a particular domain.",
    example: "Her business acumen helped the startup navigate its first turbulent year.",
    etymology: "Latin acuere — to sharpen",
    synonyms: ["shrewdness", "astuteness", "sagacity"],
  },
  {
    word: "alacrity",
    pronunciation: "/ə-ˈla-krə-tē/",
    pos: "noun",
    definition: "Brisk and cheerful readiness.",
    example: "She accepted the challenging assignment with alacrity.",
    etymology: "Latin alacritas — from alacer (lively, eager)",
    synonyms: ["eagerness", "willingness", "enthusiasm"],
  },
  {
    word: "amalgamate",
    pronunciation: "/ə-ˈmal-gə-ˌmāt/",
    pos: "verb",
    definition: "To combine or unite to form one organization or structure.",
    example: "The two departments were amalgamated to improve operational efficiency.",
    etymology: "Medieval Latin amalgamare — from Arabic al-malgham (softening plaster)",
    synonyms: ["merge", "consolidate", "fuse"],
  },
  {
    word: "anachronism",
    pronunciation: "/ə-ˈna-krə-ˌni-zəm/",
    pos: "noun",
    definition: "A thing belonging to a period other than that in which it exists.",
    example: "The typewriter on the CEO's desk was a charming anachronism in the digital age.",
    etymology: "Greek ana (against) + chronos (time)",
    synonyms: ["throwback", "relic", "holdover"],
  },
  {
    word: "antipathy",
    pronunciation: "/an-ˈti-pə-thē/",
    pos: "noun",
    definition: "A deep-seated feeling of dislike; aversion.",
    example: "His antipathy toward bureaucratic procedures was well known in the office.",
    etymology: "Greek anti (against) + pathos (feeling)",
    synonyms: ["aversion", "hostility", "animosity"],
  },
  {
    word: "apocryphal",
    pronunciation: "/ə-ˈpä-krə-fəl/",
    pos: "adjective",
    definition: "Of doubtful authenticity, although widely circulated as being true.",
    example: "The apocryphal tale of Newton's apple may not be entirely accurate.",
    etymology: "Greek apokryptein — apo (away) + kryptein (to hide)",
    synonyms: ["fictitious", "unverified", "spurious"],
  },
  {
    word: "approbation",
    pronunciation: "/ˌa-prə-ˈbā-shən/",
    pos: "noun",
    definition: "Approval or praise.",
    example: "The proposal received the committee's enthusiastic approbation.",
    etymology: "Latin approbare — ad (to) + probare (to prove good)",
    synonyms: ["approval", "endorsement", "commendation"],
  },
  {
    word: "arcane",
    pronunciation: "/är-ˈkān/",
    pos: "adjective",
    definition: "Understood by few; mysterious or secret.",
    example: "The arcane rituals of the ancient cult fascinated the anthropologists.",
    etymology: "Latin arcanus — from arca (chest, box)",
    synonyms: ["esoteric", "obscure", "cryptic"],
  },
  {
    word: "arduous",
    pronunciation: "/ˈär-jə-wəs/",
    pos: "adjective",
    definition: "Involving or requiring strenuous effort; difficult and tiring.",
    example: "The arduous climb to the summit tested even the most experienced mountaineers.",
    etymology: "Latin arduus — steep, difficult",
    synonyms: ["laborious", "strenuous", "grueling"],
  },
  {
    word: "ascetic",
    pronunciation: "/ə-ˈse-tik/",
    pos: "adjective",
    definition:
      "Characterized by severe self-discipline and abstention from all forms of indulgence.",
    example: "The monk led an ascetic life, owning nothing beyond a simple robe.",
    etymology: "Greek asketes — one who exercises, a hermit",
    synonyms: ["austere", "spartan", "abstemious"],
  },
  {
    word: "assuage",
    pronunciation: "/ə-ˈswāj/",
    pos: "verb",
    definition: "To make an unpleasant feeling less intense; to satisfy a desire or appetite.",
    example: "Nothing could assuage her grief after the sudden loss.",
    etymology: "Latin ad (to) + suavis (sweet)",
    synonyms: ["alleviate", "mitigate", "relieve"],
  },
  {
    word: "audacious",
    pronunciation: "/ȯ-ˈdā-shəs/",
    pos: "adjective",
    definition: "Showing a willingness to take surprisingly bold risks; impudent.",
    example: "The audacious rescue plan involved parachuting into hostile territory.",
    etymology: "Latin audax — from audere (to dare)",
    synonyms: ["bold", "daring", "brazen"],
  },
  {
    word: "austere",
    pronunciation: "/ȯ-ˈstir/",
    pos: "adjective",
    definition:
      "Severe or strict in manner, attitude, or appearance; having no comforts or luxuries.",
    example: "The austere dormitory rooms had only a bed, desk, and lamp.",
    etymology: "Greek austeros — harsh, severe",
    synonyms: ["stern", "spartan", "rigorous"],
  },
  {
    word: "avarice",
    pronunciation: "/ˈa-və-rəs/",
    pos: "noun",
    definition: "Extreme greed for wealth or material gain.",
    example: "His avarice led him to exploit his workers for maximum profit.",
    etymology: "Latin avaritia — from avarus (greedy)",
    synonyms: ["greed", "cupidity", "rapacity"],
  },
  {
    word: "bellicose",
    pronunciation: "/ˈbe-li-ˌkōs/",
    pos: "adjective",
    definition: "Demonstrating aggression and willingness to fight.",
    example: "The senator's bellicose rhetoric alarmed foreign diplomats.",
    etymology: "Latin bellicosus — from bellum (war)",
    synonyms: ["combative", "pugnacious", "warlike"],
  },
  {
    word: "blandishment",
    pronunciation: "/ˈblan-dish-mənt/",
    pos: "noun",
    definition: "A flattering or pleasing statement or action used to persuade someone gently.",
    example: "No amount of blandishment could convince her to change her mind.",
    etymology: "Latin blandiri — to flatter, soothe",
    synonyms: ["flattery", "cajolery", "sweet talk"],
  },
  {
    word: "bombastic",
    pronunciation: "/bäm-ˈbas-tik/",
    pos: "adjective",
    definition: "High-sounding but with little meaning; inflated.",
    example: "The politician's bombastic speech was all style and no substance.",
    etymology: "From bombast — cotton padding, hence 'inflated language'",
    synonyms: ["pompous", "grandiloquent", "turgid"],
  },
  {
    word: "burgeon",
    pronunciation: "/ˈbər-jən/",
    pos: "verb",
    definition: "To begin to grow or increase rapidly; to flourish.",
    example: "Interest in renewable energy has burgeoned over the past decade.",
    etymology: "Old French borjon — a bud",
    synonyms: ["flourish", "proliferate", "thrive"],
  },
  {
    word: "cacophony",
    pronunciation: "/kə-ˈkä-fə-nē/",
    pos: "noun",
    definition: "A harsh, discordant mixture of sounds.",
    example: "The cacophony of car horns and construction drills made conversation impossible.",
    etymology: "Greek kakos (bad) + phone (sound)",
    synonyms: ["din", "discord", "dissonance"],
  },
  {
    word: "calumny",
    pronunciation: "/ˈka-ləm-nē/",
    pos: "noun",
    definition:
      "The making of false and defamatory statements about someone to damage their reputation.",
    example: "The candidate endured months of calumny from opposition operatives.",
    etymology: "Latin calumnia — false accusation, trickery",
    synonyms: ["slander", "defamation", "libel"],
  },
  {
    word: "capricious",
    pronunciation: "/kə-ˈpri-shəs/",
    pos: "adjective",
    definition: "Given to sudden and unaccountable changes of mood or behavior.",
    example: "The capricious weather forced us to cancel the outdoor event.",
    etymology: "Italian capriccio — sudden start, from capra (goat)",
    synonyms: ["fickle", "mercurial", "erratic"],
  },
  {
    word: "castigate",
    pronunciation: "/ˈkas-tə-ˌgāt/",
    pos: "verb",
    definition: "To reprimand someone severely.",
    example: "The coach castigated the team for their lack of effort in the first half.",
    etymology: "Latin castigare — from castus (pure) + agere (to drive)",
    synonyms: ["rebuke", "chastise", "berate"],
  },
  {
    word: "catalyst",
    pronunciation: "/ˈka-tə-ləst/",
    pos: "noun",
    definition: "A person or thing that precipitates an event or change.",
    example: "The economic crisis served as a catalyst for sweeping regulatory reform.",
    etymology: "Greek katalysis — dissolution, from kata (down) + lyein (to loosen)",
    synonyms: ["stimulus", "impetus", "spark"],
  },
  {
    word: "caustic",
    pronunciation: "/ˈkȯ-stik/",
    pos: "adjective",
    definition: "Sarcastic in a scathing and bitter way; able to burn or corrode organic tissue.",
    example: "Her caustic wit made her feared in literary circles.",
    etymology: "Greek kaustikos — from kaiein (to burn)",
    synonyms: ["acerbic", "mordant", "scathing"],
  },
  {
    word: "chicanery",
    pronunciation: "/shi-ˈkā-nə-rē/",
    pos: "noun",
    definition: "The use of trickery to achieve a political, financial, or legal purpose.",
    example: "The contract was riddled with chicanery designed to exploit the unwary buyer.",
    etymology: "French chicaner — to quibble",
    synonyms: ["deception", "trickery", "subterfuge"],
  },
  {
    word: "coalesce",
    pronunciation: "/ˌkō-ə-ˈles/",
    pos: "verb",
    definition: "To come together and form one mass or whole.",
    example: "Several small protest groups coalesced into a powerful movement.",
    etymology: "Latin coalescere — co (together) + alescere (to grow)",
    synonyms: ["merge", "unite", "converge"],
  },
  {
    word: "cogent",
    pronunciation: "/ˈkō-jənt/",
    pos: "adjective",
    definition: "Clear, logical, and convincing.",
    example: "The lawyer presented a cogent argument that swayed the jury.",
    etymology: "Latin cogere — co (together) + agere (to drive)",
    synonyms: ["compelling", "persuasive", "convincing"],
  },
  {
    word: "commensurate",
    pronunciation: "/kə-ˈmen-sə-rət/",
    pos: "adjective",
    definition: "Corresponding in size or degree; in proportion.",
    example: "Her salary was commensurate with her years of experience.",
    etymology: "Latin com (together) + mensurare (to measure)",
    synonyms: ["proportionate", "corresponding", "equivalent"],
  },
  {
    word: "compendium",
    pronunciation: "/kəm-ˈpen-dē-əm/",
    pos: "noun",
    definition: "A collection of concise but detailed information about a subject.",
    example: "The professor published a compendium of research methods for graduate students.",
    etymology: "Latin compendere — to weigh together",
    synonyms: ["compilation", "anthology", "digest"],
  },
  {
    word: "concomitant",
    pronunciation: "/kən-ˈkä-mə-tənt/",
    pos: "adjective",
    definition: "Naturally accompanying or associated.",
    example: "Weight loss is a concomitant benefit of regular exercise.",
    etymology: "Latin concomitari — com (with) + comitari (to accompany)",
    synonyms: ["accompanying", "attendant", "concurrent"],
  },
  {
    word: "conflagration",
    pronunciation: "/ˌkän-flə-ˈgrā-shən/",
    pos: "noun",
    definition: "An extensive fire that destroys a great deal of land or property.",
    example:
      "The conflagration consumed three city blocks before firefighters brought it under control.",
    etymology: "Latin conflagrare — con (together) + flagrare (to burn)",
    synonyms: ["inferno", "blaze", "firestorm"],
  },
  {
    word: "contrite",
    pronunciation: "/kən-ˈtrīt/",
    pos: "adjective",
    definition: "Feeling or expressing remorse for wrongdoing.",
    example: "The contrite student apologized to the teacher in front of the whole class.",
    etymology: "Latin conterere — con (together) + terere (to rub, grind)",
    synonyms: ["remorseful", "penitent", "repentant"],
  },
  {
    word: "conundrum",
    pronunciation: "/kə-ˈnən-drəm/",
    pos: "noun",
    definition: "A confusing and difficult problem or question.",
    example: "The ethical conundrum of autonomous vehicles has no easy answer.",
    etymology: "Origin unknown; possibly pseudo-Latin Oxford slang, 16th century",
    synonyms: ["dilemma", "puzzle", "quandary"],
  },
  {
    word: "corroborate",
    pronunciation: "/kə-ˈrä-bə-ˌrāt/",
    pos: "verb",
    definition: "To confirm or give support to a statement, theory, or finding.",
    example: "The witness's testimony corroborated the defendant's alibi.",
    etymology: "Latin corroborare — con (together) + roborare (to strengthen)",
    synonyms: ["confirm", "verify", "substantiate"],
  },
  {
    word: "credulous",
    pronunciation: "/ˈkre-jə-ləs/",
    pos: "adjective",
    definition: "Having or showing too great a readiness to believe things.",
    example: "The credulous investor fell for every promise the fraudster made.",
    etymology: "Latin credulus — from credere (to believe)",
    synonyms: ["gullible", "naive", "trusting"],
  },
  {
    word: "demur",
    pronunciation: "/di-ˈmər/",
    pos: "verb",
    definition: "To raise doubts or objections; to show reluctance.",
    example: "When asked to work overtime again, she finally demurred.",
    etymology: "Latin demorari — de (away) + morari (to delay)",
    synonyms: ["object", "protest", "balk"],
  },
  {
    word: "denigrate",
    pronunciation: "/ˈde-ni-ˌgrāt/",
    pos: "verb",
    definition: "To criticize unfairly; to disparage.",
    example: "He consistently denigrated his colleagues' contributions to the project.",
    etymology: "Latin denigrare — de (completely) + nigrare (to blacken)",
    synonyms: ["disparage", "belittle", "malign"],
  },
  {
    word: "desultory",
    pronunciation: "/ˈde-səl-ˌtȯr-ē/",
    pos: "adjective",
    definition: "Lacking a plan, purpose, or enthusiasm; occurring randomly.",
    example: "Their desultory conversation drifted from topic to topic without focus.",
    etymology: "Latin desultorius — from desultor (a circus rider who leaps between horses)",
    synonyms: ["aimless", "haphazard", "erratic"],
  },
  {
    word: "diatribe",
    pronunciation: "/ˈdī-ə-ˌtrīb/",
    pos: "noun",
    definition: "A forceful and bitter verbal attack against someone or something.",
    example: "The op-ed was a diatribe against the proposed tax reform.",
    etymology: "Greek diatribe — a wearing away, discourse",
    synonyms: ["tirade", "harangue", "polemic"],
  },
  {
    word: "diffident",
    pronunciation: "/ˈdi-fə-dənt/",
    pos: "adjective",
    definition: "Modest or shy because of a lack of self-confidence.",
    example: "The diffident student rarely spoke up in class despite knowing the answers.",
    etymology: "Latin diffidere — dis (away) + fidere (to trust)",
    synonyms: ["timid", "reserved", "self-effacing"],
  },
  {
    word: "dilatory",
    pronunciation: "/ˈdi-lə-ˌtȯr-ē/",
    pos: "adjective",
    definition: "Slow to act; intended to cause delay.",
    example: "The committee used dilatory tactics to postpone the vote indefinitely.",
    etymology: "Latin dilatorius — from differre (to defer)",
    synonyms: ["sluggish", "tardy", "procrastinating"],
  },
  {
    word: "dirge",
    pronunciation: "/ˈdərj/",
    pos: "noun",
    definition: "A lament for the dead, especially one forming part of a funeral rite.",
    example: "The lone bagpiper played a haunting dirge at the graveside.",
    etymology: "Latin dirige — first word of an antiphon in the Office for the Dead",
    synonyms: ["elegy", "requiem", "lament"],
  },
  {
    word: "disabuse",
    pronunciation: "/ˌdi-sə-ˈbyüz/",
    pos: "verb",
    definition: "To persuade someone that an idea or belief is mistaken.",
    example: "The data quickly disabused the team of the notion that sales were improving.",
    etymology: "French désabuser — dis (away) + abuser (to deceive)",
    synonyms: ["undeceive", "enlighten", "correct"],
  },
  {
    word: "discordant",
    pronunciation: "/dis-ˈkȯr-dənt/",
    pos: "adjective",
    definition: "Disagreeing or incongruous; harsh and jarring in sound.",
    example: "The discordant notes from the orchestra's warm-up filled the hall.",
    etymology: "Latin discordare — dis (apart) + cor (heart)",
    synonyms: ["conflicting", "clashing", "dissonant"],
  },
  {
    word: "disparate",
    pronunciation: "/ˈdi-spə-rət/",
    pos: "adjective",
    definition: "Essentially different in kind; not allowing comparison.",
    example: "The study combined disparate data sources to form a comprehensive picture.",
    etymology: "Latin disparare — dis (apart) + parare (to prepare)",
    synonyms: ["dissimilar", "divergent", "contrasting"],
  },
  {
    word: "dissemble",
    pronunciation: "/di-ˈsem-bəl/",
    pos: "verb",
    definition: "To conceal one's true motives, feelings, or beliefs.",
    example: "She could not dissemble her disappointment when passed over for promotion.",
    etymology: "Latin dissimulare — dis (completely) + simulare (to simulate)",
    synonyms: ["disguise", "feign", "mask"],
  },
  {
    word: "dogmatic",
    pronunciation: "/dȯg-ˈma-tik/",
    pos: "adjective",
    definition: "Inclined to lay down principles as incontrovertibly true.",
    example: "His dogmatic approach left no room for alternative viewpoints.",
    etymology: "Greek dogmatikos — from dogma (opinion, decree)",
    synonyms: ["opinionated", "doctrinaire", "authoritarian"],
  },
  {
    word: "ebullient",
    pronunciation: "/i-ˈbu̇l-yənt/",
    pos: "adjective",
    definition: "Cheerful and full of energy; enthusiastic.",
    example: "Her ebullient personality lit up every room she entered.",
    etymology: "Latin ebullire — e (out) + bullire (to bubble)",
    synonyms: ["exuberant", "effervescent", "vivacious"],
  },
  {
    word: "efficacy",
    pronunciation: "/ˈe-fi-kə-sē/",
    pos: "noun",
    definition: "The ability to produce a desired or intended result.",
    example: "The efficacy of the new drug exceeded expectations in clinical trials.",
    etymology: "Latin efficacia — from efficere (to accomplish)",
    synonyms: ["effectiveness", "potency", "capability"],
  },
  {
    word: "egregious",
    pronunciation: "/i-ˈgrē-jəs/",
    pos: "adjective",
    definition: "Outstandingly bad; shocking.",
    example: "The report documented egregious violations of safety regulations.",
    etymology: "Latin egregius — e (out of) + grex (flock), originally 'outstanding'",
    synonyms: ["flagrant", "glaring", "atrocious"],
  },
  {
    word: "eloquent",
    pronunciation: "/ˈe-lə-kwənt/",
    pos: "adjective",
    definition: "Fluent or persuasive in speaking or writing.",
    example: "The eloquent defense attorney moved the jury to tears.",
    etymology: "Latin eloquens — e (out) + loqui (to speak)",
    synonyms: ["articulate", "expressive", "silver-tongued"],
  },
  {
    word: "emollient",
    pronunciation: "/i-ˈmä-lyənt/",
    pos: "adjective",
    definition: "Having the quality of softening or soothing; attempting to avoid confrontation.",
    example: "The CEO's emollient tone during the crisis helped calm investors.",
    etymology: "Latin emollire — e (out) + mollire (to soften)",
    synonyms: ["soothing", "conciliatory", "mollifying"],
  },
  {
    word: "empirical",
    pronunciation: "/im-ˈpir-i-kəl/",
    pos: "adjective",
    definition: "Based on observation or experience rather than theory or pure logic.",
    example: "The study relied on empirical data gathered over a five-year period.",
    etymology: "Greek empeirikos — from empeiria (experience)",
    synonyms: ["experimental", "observed", "evidence-based"],
  },
  {
    word: "endemic",
    pronunciation: "/en-ˈde-mik/",
    pos: "adjective",
    definition: "Regularly found among particular people or in a certain area.",
    example: "Corruption is endemic in the country's political system.",
    etymology: "Greek endemos — en (in) + demos (people)",
    synonyms: ["prevalent", "pervasive", "widespread"],
  },
  {
    word: "enervate",
    pronunciation: "/ˈe-nər-ˌvāt/",
    pos: "verb",
    definition: "To cause someone to feel drained of energy or vitality.",
    example: "The oppressive heat enervated everyone who ventured outside.",
    etymology: "Latin enervare — e (out of) + nervus (sinew)",
    synonyms: ["exhaust", "debilitate", "weaken"],
  },
  {
    word: "engender",
    pronunciation: "/in-ˈjen-dər/",
    pos: "verb",
    definition: "To cause or give rise to a feeling, situation, or condition.",
    example: "The policy changes engendered widespread resentment among employees.",
    etymology: "Latin ingenerare — in (in) + generare (to beget)",
    synonyms: ["produce", "generate", "provoke"],
  },
  {
    word: "ephemeral",
    pronunciation: "/i-ˈfe-mə-rəl/",
    pos: "adjective",
    definition: "Lasting for a very short time.",
    example: "Social media fame is often ephemeral, fading as quickly as it appears.",
    etymology: "Greek ephemeros — epi (on) + hemera (day)",
    synonyms: ["fleeting", "transient", "momentary"],
  },
  {
    word: "equivocate",
    pronunciation: "/i-ˈkwi-və-ˌkāt/",
    pos: "verb",
    definition: "To use ambiguous language so as to conceal the truth or avoid committing.",
    example: "The witness equivocated when asked about the timeline of events.",
    etymology: "Latin aequivocus — aequus (equal) + vox (voice)",
    synonyms: ["prevaricate", "hedge", "waffle"],
  },
  {
    word: "erudite",
    pronunciation: "/ˈer-yə-ˌdīt/",
    pos: "adjective",
    definition: "Having or showing great knowledge or learning.",
    example:
      "The erudite professor could discourse on topics from quantum physics to medieval poetry.",
    etymology: "Latin erudire — e (out) + rudis (untrained)",
    synonyms: ["scholarly", "learned", "knowledgeable"],
  },
  {
    word: "esoteric",
    pronunciation: "/ˌe-sə-ˈter-ik/",
    pos: "adjective",
    definition: "Intended for or likely to be understood by only a small number of people.",
    example: "The lecture on esoteric aspects of topology left most attendees bewildered.",
    etymology: "Greek esoterikos — from esotero (inner)",
    synonyms: ["arcane", "abstruse", "recondite"],
  },
  {
    word: "exacerbate",
    pronunciation: "/ig-ˈza-sər-ˌbāt/",
    pos: "verb",
    definition: "To make a problem, bad situation, or negative feeling worse.",
    example: "The drought was exacerbated by record-high temperatures.",
    etymology: "Latin exacerbare — ex (thoroughly) + acerbus (harsh, bitter)",
    synonyms: ["aggravate", "worsen", "intensify"],
  },
  {
    word: "excoriate",
    pronunciation: "/ik-ˈskȯr-ē-ˌāt/",
    pos: "verb",
    definition: "To criticize someone severely; to strip the skin off.",
    example: "The editorial excoriated the administration's handling of the crisis.",
    etymology: "Latin excoriare — ex (off) + corium (skin, hide)",
    synonyms: ["denounce", "lambaste", "censure"],
  },
  {
    word: "exigent",
    pronunciation: "/ˈek-sə-jənt/",
    pos: "adjective",
    definition: "Pressing; demanding immediate attention or action.",
    example: "The exigent circumstances forced the team to make a quick decision.",
    etymology: "Latin exigere — ex (out) + agere (to drive)",
    synonyms: ["urgent", "pressing", "imperative"],
  },
  {
    word: "extant",
    pronunciation: "/ˈek-stənt/",
    pos: "adjective",
    definition: "Still in existence; surviving.",
    example: "Only three extant copies of the original manuscript are known.",
    etymology: "Latin extare — ex (out) + stare (to stand)",
    synonyms: ["surviving", "remaining", "existing"],
  },
  {
    word: "facetious",
    pronunciation: "/fə-ˈsē-shəs/",
    pos: "adjective",
    definition: "Treating serious issues with deliberately inappropriate humor; flippant.",
    example: "His facetious remark about the budget deficit fell flat in the boardroom.",
    etymology: "Latin facetia — jest, witticism",
    synonyms: ["flippant", "tongue-in-cheek", "jocular"],
  },
  {
    word: "fastidious",
    pronunciation: "/fa-ˈsti-dē-əs/",
    pos: "adjective",
    definition: "Very attentive to and concerned about accuracy and detail.",
    example: "The fastidious editor caught every misplaced comma in the manuscript.",
    etymology: "Latin fastidium — loathing, squeamishness",
    synonyms: ["meticulous", "scrupulous", "punctilious"],
  },
  {
    word: "fecund",
    pronunciation: "/ˈfe-kənd/",
    pos: "adjective",
    definition:
      "Producing or capable of producing an abundance of offspring or new growth; fertile.",
    example: "The author's fecund imagination produced dozens of novels.",
    etymology: "Latin fecundus — fruitful",
    synonyms: ["fertile", "prolific", "productive"],
  },
  {
    word: "fervent",
    pronunciation: "/ˈfər-vənt/",
    pos: "adjective",
    definition: "Having or displaying a passionate intensity.",
    example: "She made a fervent plea for environmental action.",
    etymology: "Latin fervere — to boil, glow",
    synonyms: ["passionate", "ardent", "zealous"],
  },
  {
    word: "filibuster",
    pronunciation: "/ˈfi-lə-ˌbəs-tər/",
    pos: "noun",
    definition: "An action such as prolonged speaking to delay progress in a legislative assembly.",
    example: "The senator's twelve-hour filibuster successfully blocked the vote.",
    etymology: "Spanish filibustero — from Dutch vrijbuiter (freebooter)",
    synonyms: ["obstruction", "stonewalling", "delaying tactic"],
  },
  {
    word: "florid",
    pronunciation: "/ˈflȯr-əd/",
    pos: "adjective",
    definition: "Having a red or flushed complexion; excessively intricate or elaborate.",
    example: "The architect's florid designs divided the critics sharply.",
    etymology: "Latin floridus — from flos (flower)",
    synonyms: ["ornate", "elaborate", "flamboyant"],
  },
  {
    word: "fortuitous",
    pronunciation: "/fȯr-ˈtü-ə-təs/",
    pos: "adjective",
    definition: "Happening by accident or chance rather than design; fortunate.",
    example: "A fortuitous encounter at the conference led to their successful collaboration.",
    etymology: "Latin fortuitus — from forte (by chance)",
    synonyms: ["accidental", "serendipitous", "coincidental"],
  },
  {
    word: "fractious",
    pronunciation: "/ˈfrak-shəs/",
    pos: "adjective",
    definition: "Easily irritated; difficult to control.",
    example: "Managing the fractious coalition required all of the president's diplomatic skill.",
    etymology: "From fraction — a breaking (as if 'broken' temper)",
    synonyms: ["irritable", "unruly", "quarrelsome"],
  },
  {
    word: "garrulous",
    pronunciation: "/ˈgar-ə-ləs/",
    pos: "adjective",
    definition: "Excessively talkative, especially on trivial matters.",
    example: "The garrulous taxi driver kept up a running commentary the entire ride.",
    etymology: "Latin garrulus — from garrire (to chatter)",
    synonyms: ["loquacious", "verbose", "chatty"],
  },
  {
    word: "germane",
    pronunciation: "/jər-ˈmān/",
    pos: "adjective",
    definition: "Relevant to a subject under consideration.",
    example: "The judge ruled the evidence was not germane to the case.",
    etymology: "Latin germanus — having the same parents, genuine",
    synonyms: ["relevant", "pertinent", "applicable"],
  },
  {
    word: "gregarious",
    pronunciation: "/gri-ˈger-ē-əs/",
    pos: "adjective",
    definition: "Fond of company; sociable.",
    example: "Her gregarious nature made her a natural choice for the public relations role.",
    etymology: "Latin gregarius — from grex (flock)",
    synonyms: ["sociable", "outgoing", "convivial"],
  },
  {
    word: "hackneyed",
    pronunciation: "/ˈhak-nēd/",
    pos: "adjective",
    definition: "Lacking significance through having been overused; unoriginal.",
    example: "The speech was full of hackneyed phrases about the American dream.",
    etymology: "From hackney — a horse for ordinary riding, hence overworked",
    synonyms: ["trite", "clichéd", "banal"],
  },
  {
    word: "halcyon",
    pronunciation: "/ˈhal-sē-ən/",
    pos: "adjective",
    definition: "Denoting a period of time in the past that was idyllically happy and peaceful.",
    example: "She looked back on the halcyon days of her university years.",
    etymology: "Greek alkyon — kingfisher (mythically calming the sea)",
    synonyms: ["serene", "idyllic", "tranquil"],
  },
  {
    word: "harangue",
    pronunciation: "/hə-ˈraŋ/",
    pos: "noun",
    definition: "A lengthy and aggressive speech.",
    example: "The manager's harangue about deadlines lasted nearly an hour.",
    etymology: "Old French arengue — public address",
    synonyms: ["tirade", "diatribe", "rant"],
  },
  {
    word: "hegemony",
    pronunciation: "/hi-ˈje-mə-nē/",
    pos: "noun",
    definition: "Leadership or dominance, especially by one country or social group over others.",
    example: "The company's hegemony in the smartphone market was finally challenged.",
    etymology: "Greek hegemonia — from hegemon (leader)",
    synonyms: ["dominance", "supremacy", "authority"],
  },
  {
    word: "iconoclast",
    pronunciation: "/ī-ˈkä-nə-ˌklast/",
    pos: "noun",
    definition: "A person who attacks cherished beliefs or institutions.",
    example: "The iconoclast challenged every assumption the board held sacred.",
    etymology: "Greek eikon (image) + klan (to break)",
    synonyms: ["rebel", "dissenter", "nonconformist"],
  },
  {
    word: "immutable",
    pronunciation: "/i-ˈmyü-tə-bəl/",
    pos: "adjective",
    definition: "Unchanging over time or unable to be changed.",
    example: "The laws of thermodynamics are considered immutable.",
    etymology: "Latin immutabilis — in (not) + mutabilis (changeable)",
    synonyms: ["unchangeable", "fixed", "permanent"],
  },
  {
    word: "impervious",
    pronunciation: "/im-ˈpər-vē-əs/",
    pos: "adjective",
    definition: "Not allowing fluid to pass through; unable to be affected by.",
    example: "He seemed impervious to criticism, maintaining his calm demeanor throughout.",
    etymology: "Latin in (not) + pervius (passable)",
    synonyms: ["impenetrable", "resistant", "immune"],
  },
  {
    word: "implacable",
    pronunciation: "/im-ˈpla-kə-bəl/",
    pos: "adjective",
    definition: "Unable to be placated or appeased.",
    example: "The implacable opposition refused every compromise offered.",
    etymology: "Latin in (not) + placare (to appease)",
    synonyms: ["unrelenting", "inexorable", "unyielding"],
  },
  {
    word: "impugn",
    pronunciation: "/im-ˈpyün/",
    pos: "verb",
    definition: "To dispute the truth, validity, or honesty of a statement or motive.",
    example: "The defense attorney impugned the credibility of the prosecution's key witness.",
    etymology: "Latin impugnare — in (against) + pugnare (to fight)",
    synonyms: ["challenge", "question", "dispute"],
  },
  {
    word: "inchoate",
    pronunciation: "/in-ˈkō-ət/",
    pos: "adjective",
    definition: "Just begun and so not fully formed or developed; rudimentary.",
    example: "The inchoate plan needed considerably more detail before it could be implemented.",
    etymology: "Latin inchoare — to begin, originally 'to hitch up'",
    synonyms: ["nascent", "embryonic", "undeveloped"],
  },
  {
    word: "indigent",
    pronunciation: "/ˈin-di-jənt/",
    pos: "adjective",
    definition: "Poor; needy.",
    example: "The charity provides legal services to indigent defendants.",
    etymology: "Latin indigere — to lack, need",
    synonyms: ["impoverished", "destitute", "penurious"],
  },
  {
    word: "indolent",
    pronunciation: "/ˈin-də-lənt/",
    pos: "adjective",
    definition: "Wanting to avoid activity or exertion; lazy.",
    example: "The indolent cat spent the entire afternoon stretched across the warm windowsill.",
    etymology: "Latin indolens — in (not) + dolere (to suffer or grieve)",
    synonyms: ["lazy", "slothful", "lethargic"],
  },
  {
    word: "ingenuous",
    pronunciation: "/in-ˈjen-yə-wəs/",
    pos: "adjective",
    definition: "Innocent and unsuspecting; artlessly frank.",
    example: "Her ingenuous questions revealed she had no idea how the scheme really worked.",
    etymology: "Latin ingenuus — native, freeborn, frank",
    synonyms: ["naive", "candid", "artless"],
  },
  {
    word: "inimical",
    pronunciation: "/i-ˈni-mi-kəl/",
    pos: "adjective",
    definition: "Tending to obstruct or harm; unfriendly; hostile.",
    example: "The new regulations proved inimical to small business growth.",
    etymology: "Latin inimicus — in (not) + amicus (friend)",
    synonyms: ["hostile", "harmful", "adverse"],
  },
  {
    word: "insipid",
    pronunciation: "/in-ˈsi-pəd/",
    pos: "adjective",
    definition: "Lacking flavor; lacking vigor or interest.",
    example: "The insipid dialogue made the otherwise promising film unwatchable.",
    etymology: "Latin insipidus — in (not) + sapidus (tasty)",
    synonyms: ["bland", "vapid", "dull"],
  },
  {
    word: "intransigent",
    pronunciation: "/in-ˈtran-sə-jənt/",
    pos: "adjective",
    definition: "Unwilling or refusing to change one's views or to agree about something.",
    example: "The intransigent negotiator walked away from the deal rather than make concessions.",
    etymology: "Spanish intransigente — in (not) + Latin transigere (to come to an agreement)",
    synonyms: ["uncompromising", "inflexible", "obstinate"],
  },
  {
    word: "inveterate",
    pronunciation: "/in-ˈve-tə-rət/",
    pos: "adjective",
    definition:
      "Having a particular habit, activity, or interest that is long-established and unlikely to change.",
    example: "An inveterate traveler, he had visited over sixty countries.",
    etymology: "Latin inveterare — in (in) + vetus (old)",
    synonyms: ["habitual", "confirmed", "incorrigible"],
  },
  {
    word: "irascible",
    pronunciation: "/i-ˈra-sə-bəl/",
    pos: "adjective",
    definition: "Having or showing a tendency to be easily angered.",
    example: "The irascible professor was known for throwing chalk at inattentive students.",
    etymology: "Latin irascibilis — from irasci (to be angry)",
    synonyms: ["irritable", "hot-tempered", "cantankerous"],
  },
  {
    word: "laconic",
    pronunciation: "/lə-ˈkä-nik/",
    pos: "adjective",
    definition: "Using very few words; concise to the point of seeming rude.",
    example: 'When asked if he would surrender, the general\'s laconic reply was simply "No."',
    etymology: "Greek Lakonikos — from Lakon (Spartan), Spartans being famously terse",
    synonyms: ["terse", "succinct", "pithy"],
  },
  {
    word: "lassitude",
    pronunciation: "/ˈla-sə-ˌtüd/",
    pos: "noun",
    definition: "A state of physical or mental weariness; lack of energy.",
    example: "An overwhelming lassitude settled over the team after months of nonstop work.",
    etymology: "Latin lassitudo — from lassus (weary)",
    synonyms: ["lethargy", "fatigue", "languor"],
  },
  {
    word: "laudable",
    pronunciation: "/ˈlȯ-də-bəl/",
    pos: "adjective",
    definition: "Deserving praise and commendation.",
    example: "Her laudable efforts to reform the school system earned widespread recognition.",
    etymology: "Latin laudabilis — from laudare (to praise)",
    synonyms: ["praiseworthy", "commendable", "admirable"],
  },
  {
    word: "loquacious",
    pronunciation: "/lō-ˈkwā-shəs/",
    pos: "adjective",
    definition: "Tending to talk a great deal; talkative.",
    example: "The loquacious host kept the conversation flowing throughout dinner.",
    etymology: "Latin loquax — from loqui (to speak)",
    synonyms: ["garrulous", "verbose", "chatty"],
  },
  {
    word: "lucid",
    pronunciation: "/ˈlü-səd/",
    pos: "adjective",
    definition: "Expressed clearly; easy to understand; showing ability to think clearly.",
    example: "Despite her illness, she remained lucid enough to make her wishes known.",
    etymology: "Latin lucidus — from lux (light)",
    synonyms: ["clear", "coherent", "intelligible"],
  },
  {
    word: "magnanimous",
    pronunciation: "/mag-ˈna-nə-məs/",
    pos: "adjective",
    definition: "Very generous or forgiving, especially toward a rival or less powerful person.",
    example: "In a magnanimous gesture, the victor praised the efforts of the losing team.",
    etymology: "Latin magnanimus — magnus (great) + animus (soul)",
    synonyms: ["generous", "benevolent", "noble"],
  },
  {
    word: "mendacious",
    pronunciation: "/men-ˈdā-shəs/",
    pos: "adjective",
    definition: "Not telling the truth; lying.",
    example: "The investigation revealed a mendacious pattern of false statements to regulators.",
    etymology: "Latin mendax — lying, deceitful",
    synonyms: ["dishonest", "untruthful", "deceitful"],
  },
  {
    word: "mercurial",
    pronunciation: "/mər-ˈkyu̇r-ē-əl/",
    pos: "adjective",
    definition: "Subject to sudden or unpredictable changes of mood or mind.",
    example: "The CEO's mercurial temperament kept the entire staff on edge.",
    etymology: "Latin Mercurialis — of Mercury, the swift messenger god",
    synonyms: ["volatile", "capricious", "unpredictable"],
  },
  {
    word: "meticulous",
    pronunciation: "/mə-ˈti-kyə-ləs/",
    pos: "adjective",
    definition: "Showing great attention to detail; very careful and precise.",
    example: "The meticulous restoration of the painting took over three years.",
    etymology: "Latin meticulosus — from metus (fear), originally 'fearful, timid'",
    synonyms: ["thorough", "painstaking", "fastidious"],
  },
  {
    word: "misanthrope",
    pronunciation: "/ˈmi-sən-ˌthrōp/",
    pos: "noun",
    definition: "A person who dislikes humankind and avoids human society.",
    example: "The famous misanthrope refused all social invitations and lived as a recluse.",
    etymology: "Greek misanthropos — misein (to hate) + anthropos (man)",
    synonyms: ["cynic", "recluse", "curmudgeon"],
  },
  {
    word: "mitigate",
    pronunciation: "/ˈmi-tə-ˌgāt/",
    pos: "verb",
    definition: "To make less severe, serious, or painful.",
    example: "Sandbags were placed along the riverbank to mitigate the flood damage.",
    etymology: "Latin mitigare — mitis (soft) + agere (to drive)",
    synonyms: ["alleviate", "diminish", "lessen"],
  },
  {
    word: "mollify",
    pronunciation: "/ˈmä-lə-ˌfī/",
    pos: "verb",
    definition: "To appease the anger or anxiety of someone.",
    example: "The apology did little to mollify the outraged customers.",
    etymology: "Latin mollificare — mollis (soft) + facere (to make)",
    synonyms: ["appease", "placate", "pacify"],
  },
  {
    word: "mordant",
    pronunciation: "/ˈmȯr-dənt/",
    pos: "adjective",
    definition: "Having or showing a sharp or critical quality; biting.",
    example: "The mordant satire spared no one in the political establishment.",
    etymology: "Latin mordere — to bite",
    synonyms: ["caustic", "acerbic", "trenchant"],
  },
  {
    word: "nascent",
    pronunciation: "/ˈna-sənt/",
    pos: "adjective",
    definition: "Just beginning to develop; not yet fully formed.",
    example: "The nascent democracy still lacked many institutional safeguards.",
    etymology: "Latin nascens — from nasci (to be born)",
    synonyms: ["emerging", "budding", "incipient"],
  },
  {
    word: "nefarious",
    pronunciation: "/ni-ˈfer-ē-əs/",
    pos: "adjective",
    definition: "Wicked or criminal.",
    example: "The nefarious scheme to defraud investors was uncovered by a whistleblower.",
    etymology: "Latin nefarius — from nefas (wrong, crime)",
    synonyms: ["villainous", "heinous", "iniquitous"],
  },
  {
    word: "obdurate",
    pronunciation: "/ˈäb-də-rət/",
    pos: "adjective",
    definition: "Stubbornly refusing to change one's opinion or course of action.",
    example: "The obdurate landlord refused to make repairs despite repeated requests.",
    etymology: "Latin obdurare — ob (against) + durare (to harden)",
    synonyms: ["unyielding", "inflexible", "adamant"],
  },
  {
    word: "obsequious",
    pronunciation: "/əb-ˈsē-kwē-əs/",
    pos: "adjective",
    definition: "Obedient or attentive to an excessive degree; sycophantic.",
    example: "The obsequious assistant agreed with every word the director said.",
    etymology: "Latin obsequiosus — from obsequi (to follow, comply with)",
    synonyms: ["servile", "fawning", "sycophantic"],
  },
  {
    word: "obstinate",
    pronunciation: "/ˈäb-stə-nət/",
    pos: "adjective",
    definition: "Stubbornly refusing to change one's opinion or chosen course of action.",
    example: "His obstinate refusal to seek medical attention worried his family.",
    etymology: "Latin obstinatus — from obstinare (to persist)",
    synonyms: ["stubborn", "headstrong", "intractable"],
  },
  {
    word: "onerous",
    pronunciation: "/ˈō-nə-rəs/",
    pos: "adjective",
    definition: "Involving an amount of effort and difficulty that is oppressively burdensome.",
    example: "The onerous compliance requirements made the small firm consider shutting down.",
    etymology: "Latin onerosus — from onus (burden)",
    synonyms: ["burdensome", "taxing", "demanding"],
  },
  {
    word: "opaque",
    pronunciation: "/ō-ˈpāk/",
    pos: "adjective",
    definition: "Not able to be seen through; not transparent; hard to understand.",
    example: "The company's opaque financial disclosures frustrated analysts.",
    etymology: "Latin opacus — shady, dark",
    synonyms: ["obscure", "unclear", "impenetrable"],
  },
  {
    word: "oscillate",
    pronunciation: "/ˈä-sə-ˌlāt/",
    pos: "verb",
    definition: "To move or swing back and forth at a regular speed; to waver between extremes.",
    example: "Public opinion oscillated between support and opposition as new details emerged.",
    etymology: "Latin oscillare — to swing",
    synonyms: ["fluctuate", "vacillate", "waver"],
  },
  {
    word: "ostensible",
    pronunciation: "/ä-ˈsten-sə-bəl/",
    pos: "adjective",
    definition: "Stated or appearing to be true, but not necessarily so.",
    example:
      "The ostensible reason for the meeting was budget planning, but the real agenda was layoffs.",
    etymology: "Latin ostendere — ob (in front of) + tendere (to stretch)",
    synonyms: ["apparent", "seeming", "purported"],
  },
  {
    word: "palliate",
    pronunciation: "/ˈpa-lē-ˌāt/",
    pos: "verb",
    definition: "To make a disease or its symptoms less severe without eliminating the cause.",
    example: "The medication palliates the symptoms but does not cure the underlying condition.",
    etymology: "Latin palliare — from pallium (cloak), i.e. to cloak or conceal",
    synonyms: ["alleviate", "ease", "relieve"],
  },
  {
    word: "paradigm",
    pronunciation: "/ˈper-ə-ˌdīm/",
    pos: "noun",
    definition: "A typical example or pattern of something; a model.",
    example: "The discovery represented a paradigm shift in our understanding of genetics.",
    etymology: "Greek paradeigma — para (beside) + deiknynai (to show)",
    synonyms: ["model", "framework", "archetype"],
  },
  {
    word: "parsimonious",
    pronunciation: "/ˌpär-sə-ˈmō-nē-əs/",
    pos: "adjective",
    definition: "Unwilling to spend money or use resources; stingy.",
    example: "The parsimonious billionaire famously drove a decade-old sedan.",
    etymology: "Latin parsimonia — from parcere (to spare)",
    synonyms: ["frugal", "miserly", "tightfisted"],
  },
  {
    word: "pedantic",
    pronunciation: "/pə-ˈdan-tik/",
    pos: "adjective",
    definition: "Excessively concerned with minor details or rules; showing off learning.",
    example: "The pedantic reviewer spent three pages correcting comma usage.",
    etymology: "Italian pedante — a teacher (derogatory)",
    synonyms: ["finicky", "fussy", "nitpicking"],
  },
  {
    word: "pellucid",
    pronunciation: "/pə-ˈlü-səd/",
    pos: "adjective",
    definition: "Translucently clear; easily understood.",
    example: "Her pellucid prose made even complex scientific topics accessible.",
    etymology: "Latin pellucidus — per (through) + lucidus (clear, bright)",
    synonyms: ["transparent", "limpid", "crystalline"],
  },
  {
    word: "penurious",
    pronunciation: "/pə-ˈnu̇r-ē-əs/",
    pos: "adjective",
    definition: "Extremely poor; parsimonious; mean.",
    example: "The penurious conditions in the camp shocked the aid workers.",
    etymology: "Latin penuria — want, need",
    synonyms: ["destitute", "impoverished", "indigent"],
  },
  {
    word: "perfidious",
    pronunciation: "/pər-ˈfi-dē-əs/",
    pos: "adjective",
    definition: "Deceitful and untrustworthy.",
    example: "The perfidious ally secretly negotiated with the enemy.",
    etymology: "Latin perfidiosus — from perfidia (treachery)",
    synonyms: ["treacherous", "duplicitous", "disloyal"],
  },
  {
    word: "perfunctory",
    pronunciation: "/pər-ˈfəŋ(k)-t(ə-)rē/",
    pos: "adjective",
    definition: "Carried out with a minimum of effort or reflection.",
    example: "He gave the report only a perfunctory glance before signing it.",
    etymology: "Latin perfunctorius — from perfungi (to get through with)",
    synonyms: ["cursory", "superficial", "halfhearted"],
  },
  {
    word: "pertinacious",
    pronunciation: "/ˌpər-tə-ˈnā-shəs/",
    pos: "adjective",
    definition: "Holding firmly to an opinion or a course of action; persistent.",
    example: "The pertinacious reporter refused to drop the story despite threats.",
    etymology: "Latin pertinax — per (very) + tenax (tenacious)",
    synonyms: ["tenacious", "persistent", "dogged"],
  },
  {
    word: "phlegmatic",
    pronunciation: "/fleg-ˈma-tik/",
    pos: "adjective",
    definition: "Having an unemotional and stolidly calm disposition.",
    example: "The phlegmatic general remained calm even as artillery shook the command post.",
    etymology: "Greek phlegmatikos — from phlegma (inflammation, mucus)",
    synonyms: ["impassive", "stoic", "unflappable"],
  },
  {
    word: "placate",
    pronunciation: "/ˈplā-ˌkāt/",
    pos: "verb",
    definition: "To make someone less angry or hostile.",
    example: "The company offered refunds to placate the frustrated customers.",
    etymology: "Latin placare — to appease",
    synonyms: ["appease", "pacify", "mollify"],
  },
  {
    word: "platitude",
    pronunciation: "/ˈpla-tə-ˌtüd/",
    pos: "noun",
    definition:
      "A remark or statement that has been used too often to be interesting or thoughtful.",
    example: 'The commencement speech was filled with platitudes about "following your dreams."',
    etymology: "French, from plat (flat)",
    synonyms: ["cliché", "truism", "banality"],
  },
  {
    word: "polemical",
    pronunciation: "/pə-ˈle-mi-kəl/",
    pos: "adjective",
    definition:
      "Of or involving strongly critical, controversial, or disputatious writing or speech.",
    example: "The polemical essay drew sharp responses from both sides of the debate.",
    etymology: "Greek polemikos — from polemos (war)",
    synonyms: ["contentious", "argumentative", "controversial"],
  },
  {
    word: "pragmatic",
    pronunciation: "/prag-ˈma-tik/",
    pos: "adjective",
    definition: "Dealing with things sensibly and realistically; practical rather than idealistic.",
    example: "The pragmatic approach to policy focused on achievable goals.",
    etymology: "Greek pragmatikos — from pragma (deed, act)",
    synonyms: ["practical", "realistic", "sensible"],
  },
  {
    word: "precipitate",
    pronunciation: "/pri-ˈsi-pə-ˌtāt/",
    pos: "verb",
    definition: "To cause something to happen suddenly, unexpectedly, or prematurely.",
    example: "The CEO's resignation precipitated a sharp decline in the stock price.",
    etymology: "Latin praecipitare — prae (before) + caput (head), 'headlong'",
    synonyms: ["hasten", "trigger", "provoke"],
  },
  {
    word: "preclude",
    pronunciation: "/pri-ˈklüd/",
    pos: "verb",
    definition: "To prevent from happening; to make impossible.",
    example: "The injury precluded her participation in the championship.",
    etymology: "Latin praecludere — prae (before) + claudere (to close)",
    synonyms: ["prevent", "prohibit", "forestall"],
  },
  {
    word: "prescient",
    pronunciation: "/ˈpre-shənt/",
    pos: "adjective",
    definition: "Having or showing knowledge of events before they take place.",
    example: "Her prescient warning about the housing bubble went unheeded for years.",
    etymology: "Latin praescire — prae (before) + scire (to know)",
    synonyms: ["prophetic", "foresighted", "clairvoyant"],
  },
  {
    word: "prevaricate",
    pronunciation: "/pri-ˈver-ə-ˌkāt/",
    pos: "verb",
    definition: "To speak or act in an evasive way.",
    example: "The executive prevaricated when asked about the company's environmental record.",
    etymology: "Latin praevaricari — prae (before) + varicare (to straddle)",
    synonyms: ["equivocate", "hedge", "evade"],
  },
  {
    word: "probity",
    pronunciation: "/ˈprō-bə-tē/",
    pos: "noun",
    definition: "The quality of having strong moral principles; honesty and decency.",
    example: "The judge was known for his probity and impartiality.",
    etymology: "Latin probitas — from probus (good, honest)",
    synonyms: ["integrity", "rectitude", "uprightness"],
  },
  {
    word: "prodigal",
    pronunciation: "/ˈprä-di-gəl/",
    pos: "adjective",
    definition: "Spending money or resources freely and recklessly; wastefully extravagant.",
    example: "The prodigal heir squandered the family fortune within a decade.",
    etymology: "Latin prodigus — from prodigere (to drive forth, waste)",
    synonyms: ["extravagant", "spendthrift", "profligate"],
  },
  {
    word: "propitious",
    pronunciation: "/prə-ˈpi-shəs/",
    pos: "adjective",
    definition: "Indicating a good chance of success; favorable.",
    example: "The calm seas provided propitious conditions for the sailing expedition.",
    etymology: "Latin propitius — favorable, gracious",
    synonyms: ["auspicious", "favorable", "promising"],
  },
  {
    word: "puerile",
    pronunciation: "/ˈpyu̇r-əl/",
    pos: "adjective",
    definition: "Childishly silly and trivial.",
    example: "The puerile humor of the film appealed to teenagers but no one else.",
    etymology: "Latin puerilis — from puer (boy, child)",
    synonyms: ["juvenile", "immature", "infantile"],
  },
  {
    word: "pugnacious",
    pronunciation: "/pəg-ˈnā-shəs/",
    pos: "adjective",
    definition: "Eager or quick to argue, quarrel, or fight.",
    example: "The pugnacious debater challenged every point raised by the opposition.",
    etymology: "Latin pugnax — from pugnare (to fight)",
    synonyms: ["combative", "belligerent", "contentious"],
  },
  {
    word: "querulous",
    pronunciation: "/ˈkwer-ə-ləs/",
    pos: "adjective",
    definition: "Complaining in a petulant or whining manner.",
    example: "The querulous patient complained about everything from the food to the lighting.",
    etymology: "Latin querulus — from queri (to complain)",
    synonyms: ["whiny", "petulant", "peevish"],
  },
  {
    word: "quixotic",
    pronunciation: "/kwik-ˈsä-tik/",
    pos: "adjective",
    definition: "Exceedingly idealistic; unrealistic and impractical.",
    example:
      "His quixotic plan to end world hunger through a single app was doomed from the start.",
    etymology: "From Don Quixote — Cervantes' idealistic knight",
    synonyms: ["idealistic", "impractical", "utopian"],
  },
  {
    word: "recalcitrant",
    pronunciation: "/ri-ˈkal-sə-trənt/",
    pos: "adjective",
    definition: "Having an obstinately uncooperative attitude toward authority.",
    example: "The recalcitrant student refused to follow classroom rules.",
    etymology: "Latin recalcitrare — re (back) + calcitrare (to kick)",
    synonyms: ["defiant", "unruly", "refractory"],
  },
  {
    word: "recondite",
    pronunciation: "/ˈre-kən-ˌdīt/",
    pos: "adjective",
    definition: "Little known; abstruse; dealing with very profound or difficult subject matter.",
    example: "The recondite philosophical treatise was accessible only to specialists.",
    etymology: "Latin reconditus — re (back) + condere (to hide, store)",
    synonyms: ["obscure", "esoteric", "arcane"],
  },
  {
    word: "redoubtable",
    pronunciation: "/ri-ˈdau̇-tə-bəl/",
    pos: "adjective",
    definition: "Formidable, especially as an opponent; commanding respect.",
    example: "The redoubtable chess champion had not lost a match in over two years.",
    etymology: "French redoutable — from redouter (to dread)",
    synonyms: ["formidable", "fearsome", "imposing"],
  },
  {
    word: "refractory",
    pronunciation: "/ri-ˈfrak-tə-rē/",
    pos: "adjective",
    definition: "Stubborn or unmanageable; resistant to treatment.",
    example: "The refractory infection did not respond to standard antibiotics.",
    etymology: "Latin refractarius — stubborn, from refringere (to break open)",
    synonyms: ["recalcitrant", "obstinate", "intractable"],
  },
  {
    word: "reprobate",
    pronunciation: "/ˈre-prə-ˌbāt/",
    pos: "noun",
    definition: "An unprincipled person; a person disapproved of.",
    example: "The old reprobate was charming despite his questionable past.",
    etymology: "Latin reprobare — re (back) + probare (to approve)",
    synonyms: ["rogue", "scoundrel", "miscreant"],
  },
  {
    word: "rescind",
    pronunciation: "/ri-ˈsind/",
    pos: "verb",
    definition: "To revoke, cancel, or repeal a law, order, or agreement.",
    example: "The board voted unanimously to rescind the controversial policy.",
    etymology: "Latin rescindere — re (back) + scindere (to cut)",
    synonyms: ["revoke", "annul", "repeal"],
  },
  {
    word: "reticent",
    pronunciation: "/ˈre-tə-sənt/",
    pos: "adjective",
    definition: "Not revealing one's thoughts or feelings readily; reserved.",
    example: "She was reticent about her reasons for leaving the company.",
    etymology: "Latin reticere — re (intensifier) + tacere (to be silent)",
    synonyms: ["reserved", "taciturn", "uncommunicative"],
  },
  {
    word: "salubrious",
    pronunciation: "/sə-ˈlü-brē-əs/",
    pos: "adjective",
    definition: "Health-giving; healthy; pleasant.",
    example: "The salubrious mountain air was a welcome change from the city smog.",
    etymology: "Latin salubris — from salus (health)",
    synonyms: ["healthful", "wholesome", "beneficial"],
  },
  {
    word: "sanctimonious",
    pronunciation: "/ˌsaŋ(k)-tə-ˈmō-nē-əs/",
    pos: "adjective",
    definition: "Making a show of being morally superior to other people.",
    example: "His sanctimonious lectures about honesty rang hollow after the scandal.",
    etymology: "Latin sanctimonia — from sanctus (holy)",
    synonyms: ["self-righteous", "holier-than-thou", "pious"],
  },
  {
    word: "sanguine",
    pronunciation: "/ˈsaŋ-gwən/",
    pos: "adjective",
    definition: "Optimistic or positive, especially in a difficult situation.",
    example: "Despite the setbacks, she remained sanguine about the project's prospects.",
    etymology: "Latin sanguineus — from sanguis (blood), referring to a ruddy complexion",
    synonyms: ["optimistic", "hopeful", "confident"],
  },
  {
    word: "solicitous",
    pronunciation: "/sə-ˈli-sə-təs/",
    pos: "adjective",
    definition: "Showing interest or concern; eager or anxious to do something.",
    example: "The solicitous nurse checked on the patient every hour.",
    etymology: "Latin sollicitus — from sollus (whole) + ciere (to move, arouse)",
    synonyms: ["attentive", "concerned", "considerate"],
  },
  {
    word: "soporific",
    pronunciation: "/ˌsä-pə-ˈri-fik/",
    pos: "adjective",
    definition: "Tending to induce drowsiness or sleep.",
    example: "The professor's soporific monotone put half the lecture hall to sleep.",
    etymology: "Latin sopor (deep sleep) + facere (to make)",
    synonyms: ["sleep-inducing", "sedative", "drowsy"],
  },
  {
    word: "specious",
    pronunciation: "/ˈspē-shəs/",
    pos: "adjective",
    definition: "Superficially plausible, but actually wrong; misleading in appearance.",
    example: "The specious argument sounded convincing until you examined the evidence.",
    etymology: "Latin speciosus — from species (appearance), originally 'beautiful'",
    synonyms: ["misleading", "deceptive", "fallacious"],
  },
  {
    word: "spurious",
    pronunciation: "/ˈspyu̇r-ē-əs/",
    pos: "adjective",
    definition: "Not being what it purports to be; false or fake.",
    example: "The researcher's conclusions were based on spurious data.",
    etymology: "Latin spurius — false, illegitimate",
    synonyms: ["bogus", "fraudulent", "counterfeit"],
  },
  {
    word: "stolid",
    pronunciation: "/ˈstä-ləd/",
    pos: "adjective",
    definition: "Calm, dependable, and showing little emotion or animation.",
    example: "The stolid farmer weathered the economic downturn without complaint.",
    etymology: "Latin stolidus — dull, stupid",
    synonyms: ["impassive", "phlegmatic", "unemotional"],
  },
  {
    word: "strident",
    pronunciation: "/ˈstrī-dənt/",
    pos: "adjective",
    definition:
      "Loud and harsh; grating; presenting a point of view in an excessively forceful way.",
    example: "The strident tone of the debate left both audiences feeling hostile.",
    etymology: "Latin stridere — to creak, grate",
    synonyms: ["harsh", "shrill", "vociferous"],
  },
  {
    word: "succinct",
    pronunciation: "/sək-ˈsiŋ(k)t/",
    pos: "adjective",
    definition: "Briefly and clearly expressed.",
    example: "The CEO's succinct memo conveyed the new strategy in just three paragraphs.",
    etymology: "Latin succingere — sub (under) + cingere (to gird)",
    synonyms: ["concise", "terse", "pithy"],
  },
  {
    word: "supercilious",
    pronunciation: "/ˌsü-pər-ˈsi-lē-əs/",
    pos: "adjective",
    definition: "Behaving as though one thinks one is superior to others.",
    example: "The supercilious waiter made the diners feel unwelcome.",
    etymology: "Latin supercilium — super (above) + cilium (eyelid), i.e. raised eyebrow",
    synonyms: ["arrogant", "haughty", "condescending"],
  },
  {
    word: "supplant",
    pronunciation: "/sə-ˈplant/",
    pos: "verb",
    definition: "To supersede and replace.",
    example: "Digital streaming has largely supplanted physical media for music.",
    etymology: "Latin supplantare — sub (under) + planta (sole of the foot), to trip up",
    synonyms: ["replace", "displace", "supersede"],
  },
  {
    word: "sycophant",
    pronunciation: "/ˈsi-kə-fənt/",
    pos: "noun",
    definition: "A person who acts obsequiously toward someone important to gain advantage.",
    example: "The boardroom was full of sycophants who never challenged the chairman.",
    etymology: "Greek sykophantes — originally 'fig-shower,' an informer",
    synonyms: ["flatterer", "toady", "yes-man"],
  },
  {
    word: "taciturn",
    pronunciation: "/ˈta-sə-ˌtərn/",
    pos: "adjective",
    definition: "Reserved or uncommunicative in speech; saying little.",
    example: "The taciturn detective let his partner do all the talking.",
    etymology: "Latin taciturnus — from tacere (to be silent)",
    synonyms: ["reticent", "tight-lipped", "laconic"],
  },
  {
    word: "tenacious",
    pronunciation: "/tə-ˈnā-shəs/",
    pos: "adjective",
    definition: "Tending to keep a firm hold of something; persistent.",
    example: "The tenacious investigator spent years building the case.",
    etymology: "Latin tenax — from tenere (to hold)",
    synonyms: ["persistent", "dogged", "resolute"],
  },
  {
    word: "timorous",
    pronunciation: "/ˈti-mə-rəs/",
    pos: "adjective",
    definition: "Showing or suffering from nervousness, fear, or a lack of confidence.",
    example: "The timorous puppy hid under the bed during the thunderstorm.",
    etymology: "Latin timorosus — from timor (fear)",
    synonyms: ["fearful", "apprehensive", "timid"],
  },
  {
    word: "torpor",
    pronunciation: "/ˈtȯr-pər/",
    pos: "noun",
    definition: "A state of physical or mental inactivity; lethargy.",
    example: "The summer heat induced a torpor that made productive work impossible.",
    etymology: "Latin torpere — to be numb, sluggish",
    synonyms: ["lethargy", "sluggishness", "inertia"],
  },
  {
    word: "tractable",
    pronunciation: "/ˈtrak-tə-bəl/",
    pos: "adjective",
    definition: "Easy to control or influence; manageable.",
    example: "The once intractable problem became tractable with the new algorithm.",
    etymology: "Latin tractabilis — from tractare (to handle, manage)",
    synonyms: ["manageable", "compliant", "amenable"],
  },
  {
    word: "trenchant",
    pronunciation: "/ˈtren-chənt/",
    pos: "adjective",
    definition: "Vigorous or incisive in expression or style; sharp and penetrating.",
    example: "The trenchant analysis of the report exposed fundamental flaws in the strategy.",
    etymology: "Old French trenchant — from trencher (to cut)",
    synonyms: ["incisive", "cutting", "penetrating"],
  },
  {
    word: "turgid",
    pronunciation: "/ˈtər-jəd/",
    pos: "adjective",
    definition: "Swollen and distended; tediously pompous or bombastic in language.",
    example: "The turgid prose style made the novel nearly unreadable.",
    etymology: "Latin turgidus — from turgere (to swell)",
    synonyms: ["pompous", "overblown", "bloated"],
  },
  {
    word: "ubiquitous",
    pronunciation: "/yü-ˈbi-kwə-təs/",
    pos: "adjective",
    definition: "Present, appearing, or found everywhere.",
    example: "Smartphones have become ubiquitous in modern society.",
    etymology: "Latin ubique — everywhere",
    synonyms: ["omnipresent", "pervasive", "universal"],
  },
  {
    word: "umbrage",
    pronunciation: "/ˈəm-brij/",
    pos: "noun",
    definition: "Offense or annoyance.",
    example: "She took umbrage at the implication that her work was substandard.",
    etymology: "Latin umbra — shadow",
    synonyms: ["offense", "resentment", "indignation"],
  },
  {
    word: "unequivocal",
    pronunciation: "/ˌən-i-ˈkwi-və-kəl/",
    pos: "adjective",
    definition: "Leaving no doubt; unambiguous.",
    example: "The court's unequivocal ruling left no room for further appeals.",
    etymology: "Un- (not) + equivocal (ambiguous)",
    synonyms: ["unambiguous", "clear", "definitive"],
  },
  {
    word: "vacillate",
    pronunciation: "/ˈva-sə-ˌlāt/",
    pos: "verb",
    definition: "To alternate or waver between different opinions or actions; to be indecisive.",
    example: "She vacillated for weeks before finally accepting the job offer.",
    etymology: "Latin vacillare — to sway, waver",
    synonyms: ["waver", "hesitate", "oscillate"],
  },
  {
    word: "venerate",
    pronunciation: "/ˈve-nə-ˌrāt/",
    pos: "verb",
    definition: "To regard with great respect; to revere.",
    example: "The community venerates the founder whose vision shaped the town.",
    etymology: "Latin venerari — from venus (love, desire)",
    synonyms: ["revere", "honor", "esteem"],
  },
  {
    word: "veracious",
    pronunciation: "/və-ˈrā-shəs/",
    pos: "adjective",
    definition: "Speaking or representing the truth; truthful.",
    example: "The veracious account of the events was corroborated by multiple witnesses.",
    etymology: "Latin verax — from verus (true)",
    synonyms: ["truthful", "honest", "accurate"],
  },
  {
    word: "verbose",
    pronunciation: "/vər-ˈbōs/",
    pos: "adjective",
    definition: "Using or expressed in more words than are needed.",
    example: "The verbose report could have conveyed the same information in half the pages.",
    etymology: "Latin verbosus — from verbum (word)",
    synonyms: ["wordy", "long-winded", "prolix"],
  },
  {
    word: "viable",
    pronunciation: "/ˈvī-ə-bəl/",
    pos: "adjective",
    definition: "Capable of working successfully; feasible.",
    example: "After months of testing, the team confirmed the prototype was a viable product.",
    etymology: "French viable — from vie (life), from Latin vita",
    synonyms: ["feasible", "workable", "practicable"],
  },
  {
    word: "vindicate",
    pronunciation: "/ˈvin-də-ˌkāt/",
    pos: "verb",
    definition: "To clear someone of blame or suspicion; to show to be right or justified.",
    example: "The new evidence vindicated the scientist's original hypothesis.",
    etymology: "Latin vindicare — from vindex (claimant, defender)",
    synonyms: ["exonerate", "justify", "absolve"],
  },
  {
    word: "virulent",
    pronunciation: "/ˈvir-yə-lənt/",
    pos: "adjective",
    definition: "Extremely severe or harmful in its effects; bitterly hostile.",
    example: "The virulent strain of the virus spread rapidly through the population.",
    etymology: "Latin virulentus — from virus (poison)",
    synonyms: ["toxic", "venomous", "malignant"],
  },
  {
    word: "vociferous",
    pronunciation: "/vō-ˈsi-fə-rəs/",
    pos: "adjective",
    definition: "Vehement or clamorous; expressing feelings or opinions loudly.",
    example: "The vociferous crowd demanded an explanation from the officials.",
    etymology: "Latin vociferari — vox (voice) + ferre (to carry)",
    synonyms: ["loud", "clamorous", "strident"],
  },
  {
    word: "voluble",
    pronunciation: "/ˈväl-yə-bəl/",
    pos: "adjective",
    definition: "Speaking or spoken incessantly and fluently.",
    example: "The voluble tour guide kept the group entertained throughout the three-hour walk.",
    etymology: "Latin volubilis — from volvere (to roll)",
    synonyms: ["talkative", "fluent", "articulate"],
  },
  {
    word: "zealous",
    pronunciation: "/ˈze-ləs/",
    pos: "adjective",
    definition: "Having or showing zeal; passionate and enthusiastic.",
    example: "The zealous volunteers worked through the night to finish the project.",
    etymology: "Greek zelos — zeal, ardor",
    synonyms: ["passionate", "fervent", "enthusiastic"],
  },
];

// ---------------------------------------------------------------------------
// Formatting
// ---------------------------------------------------------------------------

function formatGreWord(w: GreWord): string {
  return [
    `*${w.word}*  ${w.pronunciation}`,
    `_${w.pos}_`,
    ``,
    `${w.definition}`,
    ``,
    `> _${w.example}_`,
    ``,
    `Etymology: ${w.etymology}`,
    `Synonyms: ${w.synonyms.join(", ")}`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Workflow factory
// ---------------------------------------------------------------------------

interface DailyGreWordSharedDeps {
  personMappingRepo: PersonMappingRepository;
  settingsRepo: SettingsRepository;
}

export type DailyGreWordDeps = AppActionRuntimeDeps<DailyGreWordSharedDeps>;

export function createDailyGreWordAction(config: ActionConfig, deps: DailyGreWordDeps): Action {
  return {
    config,
    // No inputSchema — not agent-callable
    async execute(_args: Record<string, unknown>): Promise<ActionResult> {
      try {
        // 1. Find guardian's Telegram channelUserId
        const guardians = await deps.personMappingRepo.findByBondLevel("guardian");
        if (guardians.length === 0) {
          log.warn("no guardian found, skipping GRE word");
          return { status: "error", error: "No guardian found in person mappings" };
        }

        const guardian = guardians[0];
        const telegramMapping = guardian.channelMappings.find((m) => m.channel === "telegram");
        if (!telegramMapping) {
          log.warn("guardian has no Telegram mapping, skipping GRE word");
          return { status: "error", error: "Guardian has no Telegram channel mapping" };
        }

        const channelUserId = telegramMapping.channelUserId;

        // 2. Get current word index from settings (wraps around)
        const currentIndex = (await deps.settingsRepo.get<number>("gre_word_index")) ?? 0;
        const word = GRE_WORDS[currentIndex % GRE_WORDS.length];

        // 3. Format and send
        const text = formatGreWord(word);
        await deps.appContext.runAction("send_message", {
          channel: "telegram",
          threadId: channelUserId,
          text,
          channelUserId,
        });

        // 4. Increment index (wraps via modulo on next read)
        await deps.settingsRepo.set("gre_word_index", currentIndex + 1);

        log.info("sent GRE word", { word: word.word, index: currentIndex });
        return { status: "ok", data: { word: word.word, index: currentIndex } };
      } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        log.error("daily_gre_word failed", { error: errorMsg });
        return { status: "error", error: errorMsg };
      }
    },
  };
}

export function createAction(config: ActionConfig, deps: DailyGreWordDeps): Action {
  return createDailyGreWordAction(config, deps);
}
